//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItineraryWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerary
    {
        public int Id { get; set; }
        public string itiName { get; set; }
        public string destination { get; set; }
        public string purpose { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
