//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItineraryWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Driver { get; set; }
        public string Registration { get; set; }
        public string Model { get; set; }
    }
}
